/** Practice midterm: 30 multiple choice questions for AP CSP Units 2 (Algorithms) and 3 (Data). */
export const PRACTICE_MIDTERM_QUESTIONS = [
  {
    id: 1,
    question: 'Which part of computational thinking involves breaking a large problem into smaller, manageable pieces?',
    options: ['Decomposition', 'Pattern recognition', 'Abstraction', 'Algorithm design'],
    correctIndex: 0,
  },
  {
    id: 2,
    question: 'Finding similarities and trends in problems or data is called:',
    options: ['Decomposition', 'Pattern recognition', 'Abstraction', 'Algorithm design'],
    correctIndex: 1,
  },
  {
    id: 3,
    question: 'Removing unnecessary details to focus on the main idea is known as:',
    options: ['Decomposition', 'Pattern recognition', 'Abstraction', 'Algorithm design'],
    correctIndex: 2,
  },
  {
    id: 4,
    question: 'An algorithm must be:',
    options: ['Ordered, specific, and finite', 'Short and simple', 'Written in code', 'Approximate'],
    correctIndex: 0,
  },
  {
    id: 5,
    question: 'Pseudocode is best described as:',
    options: ['Code that runs on a special computer', 'Writing code logic in plain English', 'A type of flowchart', 'Binary instructions'],
    correctIndex: 1,
  },
  {
    id: 6,
    question: 'Flowcharts are used to:',
    options: ['Store data', 'Show the steps of an algorithm visually', 'Compress files', 'Search databases'],
    correctIndex: 1,
  },
  {
    id: 7,
    question: 'Which number system do computers use to store all data?',
    options: ['Decimal (base 10)', 'Binary (base 2)', 'Hexadecimal', 'ASCII'],
    correctIndex: 1,
  },
  {
    id: 8,
    question: 'In the binary number system, each digit represents a power of:',
    options: ['10', '2', '8', '16'],
    correctIndex: 1,
  },
  {
    id: 9,
    question: 'Linear search checks items:',
    options: ['In random order', 'One by one', 'By splitting the list in half', 'Only in sorted lists'],
    correctIndex: 1,
  },
  {
    id: 10,
    question: 'Binary search requires the data to be:',
    options: ['Unsorted', 'Sorted', 'Compressed', 'Encrypted'],
    correctIndex: 1,
  },
  {
    id: 11,
    question: 'Which search is generally faster on large, sorted data sets?',
    options: ['Linear search', 'Binary search', 'They are the same speed', 'Neither'],
    correctIndex: 1,
  },
  {
    id: 12,
    question: 'ASCII is a system that:',
    options: ['Compresses files', 'Assigns numbers to letters and symbols', 'Searches databases', 'Draws flowcharts'],
    correctIndex: 1,
  },
  {
    id: 13,
    question: 'Lossless compression means:',
    options: ['Some data is permanently removed', 'You get exactly the original data back when you decompress', 'Files are always larger', 'Quality is reduced'],
    correctIndex: 1,
  },
  {
    id: 14,
    question: 'Lossy compression is often used for:',
    options: ['Text and code', 'Photos, music, and video', 'Databases', 'Spreadsheets'],
    correctIndex: 1,
  },
  {
    id: 15,
    question: 'Data abstraction helps:',
    options: ['Delete data', 'Simplify data to highlight important patterns', 'Copy files', 'Send email'],
    correctIndex: 1,
  },
  {
    id: 16,
    question: 'Tools used to store and manage data include:',
    options: ['Flowcharts only', 'Databases and spreadsheets', 'Pseudocode', 'Binary only'],
    correctIndex: 1,
  },
  {
    id: 17,
    question: 'Sorting data can make searching:',
    options: ['Slower', 'Faster', 'Impossible', 'Unnecessary'],
    correctIndex: 1,
  },
  {
    id: 18,
    question: 'Digital data representation means all data is stored using:',
    options: ['Letters', '0s and 1s (binary)', 'Colors', 'Sounds'],
    correctIndex: 1,
  },
  {
    id: 19,
    question: 'Creating clear, step-by-step instructions to solve a problem is part of:',
    options: ['Decomposition only', 'Pattern recognition only', 'Algorithm design', 'Data compression'],
    correctIndex: 2,
  },
  {
    id: 20,
    question: 'A flowchart uses shapes to represent:',
    options: ['Only numbers', 'Actions and decisions', 'Only text', 'Binary code'],
    correctIndex: 1,
  },
  {
    id: 21,
    question: 'Data can be:',
    options: ['Numbers only', 'Numbers, text, images, or sound', 'Only text', 'Only images'],
    correctIndex: 1,
  },
  {
    id: 22,
    question: 'Smaller files after compression:',
    options: ['Always lose quality', 'Save space and can transmit faster', 'Cannot be opened', 'Are always lossy'],
    correctIndex: 1,
  },
  {
    id: 23,
    question: 'Binary search repeatedly:',
    options: ['Checks the first item only', 'Splits the list in half', 'Scans every item', 'Randomly picks items'],
    correctIndex: 1,
  },
  {
    id: 24,
    question: 'Pseudocode helps you plan programs without worrying about:',
    options: ['Logic', 'Syntax (exact code rules)', 'Algorithms', 'Data'],
    correctIndex: 1,
  },
  {
    id: 25,
    question: 'Which is true about linear search?',
    options: ['It requires sorted data', 'It does NOT require sorted data', 'It is always faster than binary search', 'It splits the list in half'],
    correctIndex: 1,
  },
  {
    id: 26,
    question: 'Data compression can be:',
    options: ['Only lossless', 'Only lossy', 'Lossless or lossy', 'Neither'],
    correctIndex: 2,
  },
  {
    id: 27,
    question: 'Abstraction makes complex systems:',
    options: ['Harder to understand', 'Easier to understand', 'Faster to run', 'Larger'],
    correctIndex: 1,
  },
  {
    id: 28,
    question: 'Tradeoffs between quality and size exist in:',
    options: ['Only lossless compression', 'Data compression and storage', 'Binary search only', 'Flowcharts'],
    correctIndex: 1,
  },
  {
    id: 29,
    question: 'An algorithm is a:',
    options: ['Random set of steps', 'Clear set of instructions to solve a problem', 'Type of data', 'Compression method'],
    correctIndex: 1,
  },
  {
    id: 30,
    question: 'Searching finds data; sorting:',
    options: ['Deletes data', 'Organizes data to make searching faster', 'Compresses data', 'Encrypts data'],
    correctIndex: 1,
  },
];
