/** Semester 2 Final Practice Exam: 40 multiple choice questions for AP CSP Units 9–12 (Python, Internet, Cybersecurity, Impact of Computing). */
export const PRACTICE_SEMESTER_2_QUESTIONS = [
  // Unit 9 – Lists and More in Python
  {
    id: 1,
    question: 'In Python, a string is best described as:',
    options: ['A number', 'A sequence of characters (text)', 'A loop', 'A database'],
    correctIndex: 1,
    topic: 'Strings in Python',
    explanation: 'Strings are sequences of characters used to store and manipulate text in Python.',
  },
  {
    id: 2,
    question: 'A list in Python is used to:',
    options: ['Store a single value', 'Store a collection of multiple values', 'Compress files', 'Search the web'],
    correctIndex: 1,
    topic: 'Lists in Python',
    explanation: 'Lists are collections that allow you to store multiple values together and modify them easily.',
  },
  {
    id: 3,
    question: 'Reading pseudocode helps you:',
    options: ['Write faster code', 'Understand logic without worrying about exact syntax', 'Fix hardware problems', 'Compress images'],
    correctIndex: 1,
    topic: 'Reading Pseudocode',
    explanation: 'Pseudocode focuses on the logic and flow of a program so you can convert ideas into real code.',
  },
  {
    id: 4,
    question: 'Python lists allow you to:',
    options: ['Only read values', 'Store and modify data easily', 'Encrypt passwords', 'Create the Internet'],
    correctIndex: 1,
    topic: 'Lists in Python',
    explanation: 'Lists in Python are mutable—you can add, remove, and change items.',
  },
  {
    id: 5,
    question: 'Understanding pseudocode helps when:',
    options: ['Installing routers', 'Converting algorithm logic into actual code', 'Encrypting cookies', 'Building physical networks'],
    correctIndex: 1,
    topic: 'Reading Pseudocode',
    explanation: 'Pseudocode bridges the gap between an idea and working code in Python or any language.',
  },
  // Unit 10 – The Internet
  {
    id: 6,
    question: 'The Internet is best described as:',
    options: ['A single computer', 'A global network of connected computers', 'A programming language', 'A type of database'],
    correctIndex: 1,
    topic: 'Internet Overview',
    explanation: 'The Internet is a global network of connected computers that allows information to be shared worldwide.',
  },
  {
    id: 7,
    question: 'Servers, clients, and routers:',
    options: ['Are the same thing', 'Work together to transmit data on the Internet', 'Only exist in Python', 'Store passwords'],
    correctIndex: 1,
    topic: 'Internet Systems',
    explanation: 'Servers provide resources, clients request them, and routers direct data between networks.',
  },
  {
    id: 8,
    question: 'HTML is used to:',
    options: ['Write Python code', 'Structure content on webpages', 'Encrypt data', 'Run databases'],
    correctIndex: 1,
    topic: 'HTML',
    explanation: 'HTML uses tags to structure content on the web—text, images, links, and more.',
  },
  {
    id: 9,
    question: 'Devices on a network need unique addresses (IP addresses) to:',
    options: ['Increase speed', 'Ensure data reaches the right destination', 'Compress files', 'Display images'],
    correctIndex: 1,
    topic: 'Addressing',
    explanation: 'IP addresses uniquely identify devices so data knows where to go.',
  },
  {
    id: 10,
    question: 'When data is sent over the Internet, it is typically split into:',
    options: ['One large file', 'Small pieces called packets', 'Binary only', 'Strings'],
    correctIndex: 1,
    topic: 'Packets',
    explanation: 'Data is split into packets that travel independently and are reassembled at the destination.',
  },
  {
    id: 11,
    question: 'HTTPS helps:',
    options: ['Speed up the Internet', 'Secure web communication by encrypting data', 'Store cookies', 'Display HTML'],
    correctIndex: 1,
    topic: 'HTTPS',
    explanation: 'HTTPS encrypts data between your browser and the website to protect from eavesdropping.',
  },
  {
    id: 12,
    question: 'DNS (Domain Name System) is responsible for:',
    options: ['Compressing websites', 'Converting domain names (like google.com) to IP addresses', 'Creating passwords', 'Storing lists'],
    correctIndex: 1,
    topic: 'DNS',
    explanation: 'DNS translates human-readable domain names into the IP addresses computers use.',
  },
  {
    id: 13,
    question: 'Fault tolerance means systems:',
    options: ['Never fail', 'Continue working despite some failures', 'Are always fast', 'Require no maintenance'],
    correctIndex: 1,
    topic: 'Fault Tolerance',
    explanation: 'Fault tolerance is the ability to keep working when parts of the system fail; redundancy helps.',
  },
  {
    id: 14,
    question: 'In parallel computing:',
    options: ['One task runs at a time', 'Multiple tasks run at the same time', 'Data is never split', 'The Internet is slower'],
    correctIndex: 1,
    topic: 'Parallel Computing',
    explanation: 'Parallel computing runs multiple tasks simultaneously, often on multiple processors.',
  },
  {
    id: 15,
    question: 'In distributed computing:',
    options: ['All work is done on one computer', 'Tasks are spread across multiple computers', 'Data cannot be shared', 'Packets are not used'],
    correctIndex: 1,
    topic: 'Distributed Computing',
    explanation: 'Distributed computing spreads tasks across many computers that work together.',
  },
  {
    id: 16,
    question: 'A protocol in networking is:',
    options: ['A type of cookie', 'A set of rules that define how devices communicate', 'A Python list', 'An encryption key'],
    correctIndex: 1,
    topic: 'Internet Protocols',
    explanation: 'Protocols are agreed-upon rules (e.g., TCP/IP, HTTP) that devices use to communicate.',
  },
  {
    id: 17,
    question: 'Redundancy in networks helps:',
    options: ['Delete duplicate data', 'Prevent system failure by having backup paths', 'Simplify passwords', 'Reduce packet size'],
    correctIndex: 1,
    topic: 'Redundancy',
    explanation: 'Redundancy means backup paths so data can still reach its destination if one route fails.',
  },
  // Unit 11 – Cybersecurity
  {
    id: 18,
    question: 'Cybersecurity focuses on:',
    options: ['Making websites faster', 'Protecting systems and data from attacks', 'Creating new programming languages', 'Designing HTML'],
    correctIndex: 1,
    topic: 'Cybersecurity Overview',
    explanation: 'Cybersecurity protects systems, networks, and data from unauthorized access and attacks.',
  },
  {
    id: 19,
    question: 'PII stands for:',
    options: ['Personal Internet Identifier', 'Personally Identifiable Information', 'Programming Input Interface', 'Protected Information Index'],
    correctIndex: 1,
    topic: 'PII',
    explanation: 'PII is any data that can identify a specific person—name, address, SSN, email—and must be protected.',
  },
  {
    id: 20,
    question: 'Cookies are small pieces of data that:',
    options: ['Encrypt your password', 'Websites store on your device to remember information', 'Delete your browsing history', 'Speed up DNS'],
    correctIndex: 1,
    topic: 'Cookies',
    explanation: 'Cookies are small files websites store on your device to remember login status and preferences.',
  },
  {
    id: 21,
    question: 'A digital footprint is:',
    options: ['A type of encryption', 'The data you leave online through your activities', 'A programming loop', 'A network router'],
    correctIndex: 1,
    topic: 'Digital Footprint',
    explanation: 'Your digital footprint is the trail of data you create online; it can be long-lasting.',
  },
  {
    id: 22,
    question: 'Strong passwords are typically:',
    options: ['Short and simple', 'Long and unique', 'Your name and birth year', 'The same for all accounts'],
    correctIndex: 1,
    topic: 'Passwords',
    explanation: 'Strong passwords are long, unique, and combine letters, numbers, and symbols.',
  },
  {
    id: 23,
    question: 'Encryption:',
    options: ['Makes data easier to read', 'Converts readable data into unreadable form that requires a key to decrypt', 'Deletes old data', 'Speeds up the Internet'],
    correctIndex: 1,
    topic: 'Encryption',
    explanation: 'Encryption transforms readable data into unreadable form; only the correct key can decrypt it.',
  },
  {
    id: 24,
    question: 'Cryptography is used to:',
    options: ['Design websites', 'Encode information to keep it secret from unauthorized users', 'Create lists in Python', 'Route packets'],
    correctIndex: 1,
    topic: 'Cryptography',
    explanation: 'Cryptography uses math to encode information so only authorized users can read it.',
  },
  {
    id: 25,
    question: 'Internet privacy concerns include:',
    options: ['How fast data travels', 'How data is collected, used, and who has access to it', 'The number of routers', 'HTML structure'],
    correctIndex: 1,
    topic: 'Internet Privacy',
    explanation: 'Privacy involves who collects your data, how it is used, and whether you have control.',
  },
  // Unit 12 – Impact of Computing
  {
    id: 26,
    question: 'Computing affects society and culture in ways that can be:',
    options: ['Only positive', 'Only negative', 'Both positive and negative', 'Neither'],
    correctIndex: 2,
    topic: 'Impact of Computing',
    explanation: 'Computing has broad impact on society and culture, with both benefits and drawbacks.',
  },
  {
    id: 27,
    question: 'Machine learning is when:',
    options: ['Computers only follow fixed rules', 'Computers learn patterns from data', 'Data is never stored', 'The Internet is not used'],
    correctIndex: 1,
    topic: 'Machine Learning',
    explanation: 'Machine learning lets computers learn patterns from data for recommendations and predictions.',
  },
  {
    id: 28,
    question: 'Training data is the data that:',
    options: ['Deletes old files', 'A model learns from to make predictions', 'Only encrypts passwords', 'Runs DNS'],
    correctIndex: 1,
    topic: 'Training Data',
    explanation: 'Models learn from training data. The quality and content of this data shape how the model behaves.',
  },
  {
    id: 29,
    question: 'If training data is biased, the model is likely to:',
    options: ['Run faster', 'Produce biased outcomes', 'Ignore all data', 'Stop learning'],
    correctIndex: 1,
    topic: 'Training Data & Bias',
    explanation: 'Biased data creates biased outcomes. Models reflect the patterns—and biases—in the data they are trained on.',
  },
  {
    id: 30,
    question: 'Algorithmic bias means:',
    options: ['Algorithms are always correct', 'Algorithms may unfairly favor or harm certain groups', 'Algorithms cannot use data', 'Bias does not exist in software'],
    correctIndex: 1,
    topic: 'Algorithmic Bias',
    explanation: 'Algorithmic bias occurs when algorithms produce unfair results for certain groups; it is an important ethical concern.',
  },
  {
    id: 31,
    question: 'Why is it important to consider bias in computing?',
    options: ['It makes code run slower', 'Unfair outcomes can harm people and reinforce inequality', 'It only affects one group', 'Bias cannot be fixed'],
    correctIndex: 1,
    topic: 'Algorithmic Bias',
    explanation: 'Biased systems can harm people and reinforce inequality. Considering and mitigating bias is an ethical responsibility.',
  },
  {
    id: 32,
    question: 'Recommendation systems (e.g., for videos or products) often use:',
    options: ['Only manual rules', 'Machine learning from user data', 'No data at all', 'Only encryption'],
    correctIndex: 1,
    topic: 'Machine Learning',
    explanation: 'Recommendation systems use machine learning to learn from user behavior and suggest relevant content.',
  },
  {
    id: 33,
    question: 'The impact of computing on individuals and society should be considered:',
    options: ['Only after release', 'As part of responsible design and ethics', 'Only by users', 'Never'],
    correctIndex: 1,
    topic: 'Impact of Computing',
    explanation: 'Responsible design considers the impact of computing on people and society, including fairness and privacy.',
  },
  {
    id: 34,
    question: 'Routing on the Internet:',
    options: ['Deletes data', 'Determines the path data takes to reach its destination', 'Compresses files', 'Creates websites'],
    correctIndex: 1,
    topic: 'Routing',
    explanation: 'Routing is the process of determining the path for data from sender to receiver.',
  },
  {
    id: 35,
    question: 'A client in a network:',
    options: ['Only sends data', 'Requests and receives resources from servers', 'Encrypts all packets', 'Creates DNS records'],
    correctIndex: 1,
    topic: 'Clients and Servers',
    explanation: 'A client requests services or resources; your browser is a client that requests web pages from servers.',
  },
  {
    id: 36,
    question: 'Protecting your PII online is important because:',
    options: ['It slows down websites', 'It can be used for identity theft or misuse if exposed', 'Routers require it', 'Packets need it'],
    correctIndex: 1,
    topic: 'PII and Privacy',
    explanation: 'PII can be misused for identity theft or fraud; protecting it is essential.',
  },
  {
    id: 37,
    question: 'Wired and wireless networks both:',
    options: ['Use the same physical cables', 'Connect devices to share data', 'Require no addressing', 'Cannot use encryption'],
    correctIndex: 1,
    topic: 'Networks',
    explanation: 'Both wired and wireless networks connect devices to share data; they use different physical means.',
  },
  {
    id: 38,
    question: 'When you visit a website, your browser:',
    options: ['Only receives data', 'Acts as a client requesting content from a server', 'Creates the HTML', 'Encrypts the DNS'],
    correctIndex: 1,
    topic: 'Client-Server Model',
    explanation: 'Your browser acts as a client, sending a request to the server and receiving the webpage content.',
  },
  {
    id: 39,
    question: 'Mitigating algorithmic bias might include:',
    options: ['Ignoring training data', 'Using diverse, representative data and testing for fairness', 'Removing all algorithms', 'Only using one demographic'],
    correctIndex: 1,
    topic: 'Algorithmic Bias',
    explanation: 'Mitigating bias can involve diverse training data, testing for unfair outcomes, and ongoing evaluation.',
  },
  {
    id: 40,
    question: 'Computing can benefit society by:',
    options: ['Only replacing jobs', 'Improving communication, healthcare, education, and access to information', 'Only storing data', 'Eliminating privacy'],
    correctIndex: 1,
    topic: 'Impact of Computing',
    explanation: 'Computing can improve many areas of life while also raising ethical questions that need to be addressed.',
  },
];
