/** Semester 1 Practice Exam: 40 multiple choice questions for AP CSP Units 2–6 (Algorithms, Data, Scratch, App Lab, Software Development). */
export const PRACTICE_SEMESTER_1_QUESTIONS = [
  // Unit 2 – Algorithms
  {
    id: 1,
    question: 'Which part of computational thinking involves breaking a large problem into smaller, manageable pieces?',
    options: ['Decomposition', 'Pattern recognition', 'Abstraction', 'Algorithm design'],
    correctIndex: 0,
    topic: 'Computational Thinking',
    explanation: 'Decomposition is breaking a large problem into smaller, manageable subproblems so you can solve them step by step.',
  },
  {
    id: 2,
    question: 'Finding similarities and trends in problems or data is called:',
    options: ['Decomposition', 'Pattern recognition', 'Abstraction', 'Algorithm design'],
    correctIndex: 1,
    topic: 'Computational Thinking',
    explanation: 'Pattern recognition is identifying similarities and trends. Once you spot patterns, you can reuse solutions or predict what comes next.',
  },
  {
    id: 3,
    question: 'An algorithm must be:',
    options: ['Ordered, specific, and finite', 'Short and simple', 'Written in code', 'Approximate'],
    correctIndex: 0,
    topic: 'Algorithms',
    explanation: 'An algorithm is a clear set of instructions that must be ordered (defined sequence), specific (unambiguous), and finite (eventually stops).',
  },
  {
    id: 4,
    question: 'Pseudocode is best described as:',
    options: ['Code that runs on a special computer', 'Writing code logic in plain English', 'A type of flowchart', 'Binary instructions'],
    correctIndex: 1,
    topic: 'Pseudocode',
    explanation: 'Pseudocode uses plain English to describe program logic. It helps you plan without worrying about exact syntax.',
  },
  {
    id: 5,
    question: 'Flowcharts are used to:',
    options: ['Store data', 'Show the steps of an algorithm visually', 'Compress files', 'Search databases'],
    correctIndex: 1,
    topic: 'Flowcharts',
    explanation: 'Flowcharts are visual diagrams that show steps, decisions, and flow of an algorithm using shapes like rectangles and diamonds.',
  },
  {
    id: 6,
    question: 'Removing unnecessary details to focus on the main idea is known as:',
    options: ['Decomposition', 'Pattern recognition', 'Abstraction', 'Algorithm design'],
    correctIndex: 2,
    topic: 'Abstraction',
    explanation: 'Abstraction means hiding or removing unnecessary details so you can focus on what matters. It makes complex systems easier to understand.',
  },
  {
    id: 7,
    question: 'Creating clear, step-by-step instructions to solve a problem is part of:',
    options: ['Decomposition only', 'Pattern recognition only', 'Algorithm design', 'Data compression'],
    correctIndex: 2,
    topic: 'Algorithm design',
    explanation: 'Algorithm design is the skill of creating clear, ordered, step-by-step instructions to solve a problem.',
  },
  // Unit 3 – Data
  {
    id: 8,
    question: 'Which number system do computers use to store all data?',
    options: ['Decimal (base 10)', 'Binary (base 2)', 'Hexadecimal', 'ASCII'],
    correctIndex: 1,
    topic: 'Binary',
    explanation: 'Computers store all data as binary (0s and 1s) because digital circuits can only reliably represent two states: on or off.',
  },
  {
    id: 9,
    question: 'In the binary number system, each digit represents a power of:',
    options: ['10', '2', '8', '16'],
    correctIndex: 1,
    topic: 'Binary',
    explanation: 'Binary is base-2. Each bit represents a power of 2. For example, 101 in binary = 1×2² + 0×2¹ + 1×2⁰ = 5 in decimal.',
  },
  {
    id: 10,
    question: 'Linear search checks items:',
    options: ['In random order', 'One by one', 'By splitting the list in half', 'Only in sorted lists'],
    correctIndex: 1,
    topic: 'Search Algorithms',
    explanation: 'Linear search goes through items one by one from the start until it finds the target or reaches the end. It does not require a sorted list.',
  },
  {
    id: 11,
    question: 'Binary search requires the data to be:',
    options: ['Unsorted', 'Sorted', 'Compressed', 'Encrypted'],
    correctIndex: 1,
    topic: 'Search Algorithms',
    explanation: 'Binary search repeatedly splits the list in half. This only works when the data is sorted so it knows which half to search next.',
  },
  {
    id: 12,
    question: 'ASCII is a system that:',
    options: ['Compresses files', 'Assigns numbers to letters and symbols', 'Searches databases', 'Draws flowcharts'],
    correctIndex: 1,
    topic: 'ASCII',
    explanation: 'ASCII assigns a unique number to each letter, digit, and common symbol so text can be stored and transmitted digitally.',
  },
  {
    id: 13,
    question: 'Lossless compression means:',
    options: ['Some data is permanently removed', 'You get exactly the original data back when you decompress', 'Files are always larger', 'Quality is reduced'],
    correctIndex: 1,
    topic: 'Data Compression',
    explanation: 'Lossless compression reduces file size without losing any data. When you decompress, you get back exactly what you had before.',
  },
  {
    id: 14,
    question: 'Lossy compression is often used for:',
    options: ['Text and code', 'Photos, music, and video', 'Databases', 'Spreadsheets'],
    correctIndex: 1,
    topic: 'Data Compression',
    explanation: 'Lossy compression discards some data for smaller files. For photos, music, and video, small quality losses are often acceptable.',
  },
  {
    id: 15,
    question: 'Data abstraction helps:',
    options: ['Delete data', 'Simplify data to highlight important patterns', 'Copy files', 'Send email'],
    correctIndex: 1,
    topic: 'Data Abstraction',
    explanation: 'Data abstraction simplifies complex data by focusing on important patterns and hiding unnecessary details.',
  },
  {
    id: 16,
    question: 'Sorting data can make searching:',
    options: ['Slower', 'Faster', 'Impossible', 'Unnecessary'],
    correctIndex: 1,
    topic: 'Search & Sorting',
    explanation: 'Sorted data allows binary search to work, which is much faster than linear search on large data sets.',
  },
  {
    id: 17,
    question: 'Data can be:',
    options: ['Numbers only', 'Numbers, text, images, or sound', 'Only text', 'Only images'],
    correctIndex: 1,
    topic: 'Data Overview',
    explanation: 'Data is information collected for analysis or decision-making. It can be numbers, text, images, sound, and more.',
  },
  {
    id: 18,
    question: 'Tools used to store and manage data include:',
    options: ['Flowcharts only', 'Databases and spreadsheets', 'Pseudocode', 'Binary only'],
    correctIndex: 1,
    topic: 'Data Systems',
    explanation: 'Databases and spreadsheets are common tools for storing, organizing, and managing data.',
  },
  // Unit 4 – Programming with Scratch
  {
    id: 19,
    question: 'In Scratch, a "repeat (n)" loop:',
    options: ['Runs forever', 'Runs the inside blocks a specific number of times, then stops', 'Runs until a condition is true', 'Only runs once'],
    correctIndex: 1,
    topic: 'Loops in Scratch',
    explanation: 'The repeat (n) loop runs the blocks inside it a specific number of times (n), then stops. It is used when you know how many times to repeat.',
  },
  {
    id: 20,
    question: 'A "forever" loop in Scratch:',
    options: ['Runs a set number of times', 'Keeps running until a condition is true', 'Keeps running until the program is stopped', 'Runs only once'],
    correctIndex: 2,
    topic: 'Loops in Scratch',
    explanation: 'The forever loop keeps running the blocks inside it without stopping until the program or script is stopped by the user.',
  },
  {
    id: 21,
    question: 'A "repeat until" loop in Scratch:',
    options: ['Runs a fixed number of times', 'Runs forever', 'Keeps running until a condition becomes true', 'Never runs'],
    correctIndex: 2,
    topic: 'Loops in Scratch',
    explanation: 'The repeat until loop keeps running the inside blocks until a condition becomes true (e.g., until a sprite touches a color).',
  },
  {
    id: 22,
    question: 'Why are loops useful in Scratch?',
    options: ['They make the program slower', 'They repeat actions automatically so you do not copy the same blocks over and over', 'They delete sprites', 'They only work with one block'],
    correctIndex: 1,
    topic: 'Loops in Scratch',
    explanation: 'Loops repeat actions automatically, reducing repetition and making programs shorter and easier to change.',
  },
  {
    id: 23,
    question: 'Which Scratch loop would you use to move a sprite 10 steps, 5 times?',
    options: ['forever', 'repeat until', 'repeat (5)', 'None of these'],
    correctIndex: 2,
    topic: 'Loops in Scratch',
    explanation: 'When you know exactly how many times to repeat (5), use "repeat (5)" with "move 10 steps" inside it.',
  },
  {
    id: 24,
    question: 'Which Scratch loop would you use to keep a score display updating as long as the game runs?',
    options: ['repeat (10)', 'repeat until', 'forever', 'None—you cannot do this'],
    correctIndex: 2,
    topic: 'Loops in Scratch',
    explanation: 'A forever loop is used when you want something to keep running for the whole time the program is active, like updating a score.',
  },
  // Unit 5 – Programming with App Lab (Boolean logic)
  {
    id: 25,
    question: 'Boolean logic uses values that are:',
    options: ['Numbers only', 'True and false', 'Text only', 'Decimals'],
    correctIndex: 1,
    topic: 'Boolean Logic',
    explanation: 'Boolean logic works with true and false values. It is used to control decision-making in programs.',
  },
  {
    id: 26,
    question: 'In Boolean logic, AND gives true when:',
    options: ['At least one condition is true', 'Both conditions are true', 'No conditions are true', 'Only the first condition is true'],
    correctIndex: 1,
    topic: 'Boolean Logic',
    explanation: 'AND is true only when both conditions are true. If either is false, the result is false.',
  },
  {
    id: 27,
    question: 'In Boolean logic, OR gives true when:',
    options: ['Both conditions must be true', 'At least one condition is true', 'Both conditions must be false', 'Only the second condition is true'],
    correctIndex: 1,
    topic: 'Boolean Logic',
    explanation: 'OR is true when at least one of the conditions is true. Only when both are false is the result false.',
  },
  {
    id: 28,
    question: 'NOT in Boolean logic:',
    options: ['Adds two values', 'Reverses true to false and false to true', 'Compares numbers only', 'Is used only in loops'],
    correctIndex: 1,
    topic: 'Boolean Logic',
    explanation: 'NOT flips the value: NOT true is false, and NOT false is true. It inverts a Boolean condition.',
  },
  {
    id: 29,
    question: 'Boolean logic is often used in programs to:',
    options: ['Store images', 'Control decision-making (e.g., when to run certain code)', 'Compress files', 'Draw flowcharts'],
    correctIndex: 1,
    topic: 'Boolean Logic',
    explanation: 'Boolean logic (AND, OR, NOT) controls when certain parts of a program run—for example, in conditionals and loops.',
  },
  {
    id: 30,
    question: 'If A is true and B is false, what is (A AND B)?',
    options: ['True', 'False', 'Neither', 'Both'],
    correctIndex: 1,
    topic: 'Boolean Logic',
    explanation: 'AND is true only when both are true. Since B is false, (A AND B) is false.',
  },
  // Unit 6 – Software Development
  {
    id: 31,
    question: 'The software development cycle typically includes:',
    options: ['Only coding', 'Planning, building, and maintaining software (design, coding, testing, updates)', 'Only testing', 'Only design'],
    correctIndex: 1,
    topic: 'Software Development Cycle',
    explanation: 'The software development cycle is the process of planning, building, and maintaining software, including design, coding, testing, and updates.',
  },
  {
    id: 32,
    question: 'Skipping stages in the development cycle often leads to:',
    options: ['Faster delivery only', 'Bugs and problems', 'Smaller code', 'Fewer users'],
    correctIndex: 1,
    topic: 'Stages of Development',
    explanation: 'Each stage (design, coding, testing, etc.) has a purpose. Skipping stages often leads to more bugs and harder-to-maintain software.',
  },
  {
    id: 33,
    question: 'Ethical issues in software development can include:',
    options: ['Only speed of the program', 'Fairness, privacy, and accessibility', 'Only file size', 'Only programming language'],
    correctIndex: 1,
    topic: 'Ethical Issues',
    explanation: 'Ethical issues include how technology affects people: fairness, privacy, accessibility, and responsibility for impact.',
  },
  {
    id: 34,
    question: 'Developers are responsible for:',
    options: ['Only writing code', 'The impact of their software and using technology to benefit society', 'Only fixing hardware', 'Only designing logos'],
    correctIndex: 1,
    topic: 'Ethical Use and Responsibility',
    explanation: 'Developers are responsible for the impact of their software. Technology should be used in ways that benefit society.',
  },
  {
    id: 35,
    question: 'Different development cycle methods (e.g., agile, waterfall) are used to:',
    options: ['Replace coding', 'Plan and build software in different ways; teams choose the right approach', 'Only speed up the computer', 'Only design graphics'],
    correctIndex: 1,
    topic: 'Development Cycle Methods',
    explanation: 'Different methods offer different ways to plan and build software. Teams compare and choose the approach that fits the project.',
  },
  {
    id: 36,
    question: 'Testing in the development cycle helps:',
    options: ['Remove all need for design', 'Find bugs and ensure the software works as intended', 'Replace maintenance', 'Only make the program faster'],
    correctIndex: 1,
    topic: 'Software Development Cycle',
    explanation: 'Testing is a stage where you check that the software works correctly and find bugs before or after release.',
  },
  // Mixed / reinforcement
  {
    id: 37,
    question: 'Digital data representation means all data is stored using:',
    options: ['Letters', '0s and 1s (binary)', 'Colors', 'Sounds'],
    correctIndex: 1,
    topic: 'Binary',
    explanation: 'Everything—text, numbers, images, sound—is ultimately stored as binary (0s and 1s) that computers can process.',
  },
  {
    id: 38,
    question: 'Binary search repeatedly:',
    options: ['Checks the first item only', 'Splits the list in half', 'Scans every item', 'Randomly picks items'],
    correctIndex: 1,
    topic: 'Search Algorithms',
    explanation: 'Binary search repeatedly divides the search space in half and checks the middle item until the target is found or the space is empty.',
  },
  {
    id: 39,
    question: 'An algorithm is a:',
    options: ['Random set of steps', 'Clear set of instructions to solve a problem', 'Type of data', 'Compression method'],
    correctIndex: 1,
    topic: 'Algorithms',
    explanation: 'An algorithm is a clear, ordered set of instructions to solve a problem. It must be specific, unambiguous, and finite.',
  },
  {
    id: 40,
    question: 'Searching finds data; sorting:',
    options: ['Deletes data', 'Organizes data to make searching faster', 'Compresses data', 'Encrypts data'],
    correctIndex: 1,
    topic: 'Search & Sorting',
    explanation: 'Sorting puts data in order. Once sorted, you can use faster search algorithms like binary search.',
  },
];
