/** Practice midterm 2: 30 multiple choice questions for AP CSP Units 9 (Python), 10 (Internet), and 11 (Cybersecurity). */
export const PRACTICE_MIDTERM_2_QUESTIONS = [
  {
    id: 1,
    question: 'In Python, a string is best described as:',
    options: ['A number', 'A sequence of characters (text)', 'A loop', 'A database'],
    correctIndex: 1,
    topic: 'Strings in Python',
    explanation: 'Strings are sequences of characters used to store and manipulate text in Python. They can contain letters, numbers, symbols, and spaces.',
  },
  {
    id: 2,
    question: 'A list in Python is used to:',
    options: ['Store a single value', 'Store a collection of multiple values', 'Compress files', 'Search the web'],
    correctIndex: 1,
    topic: 'Lists in Python',
    explanation: 'Lists are collections that allow you to store multiple values together. They can be modified (add, remove, change items) and are useful for grouping related data.',
  },
  {
    id: 3,
    question: 'Reading pseudocode helps you:',
    options: ['Write faster code', 'Understand logic without worrying about exact syntax', 'Fix hardware problems', 'Compress images'],
    correctIndex: 1,
    topic: 'Reading Pseudocode',
    explanation: 'Pseudocode focuses on the logic and flow of a program. Understanding it helps you convert ideas into real code without getting stuck on syntax details.',
  },
  {
    id: 4,
    question: 'The Internet is best described as:',
    options: ['A single computer', 'A global network of connected computers', 'A programming language', 'A type of database'],
    correctIndex: 1,
    topic: 'Internet Overview',
    explanation: 'The Internet is a global network of connected computers that allows information to be shared worldwide. It is often called a "network of networks."',
  },
  {
    id: 5,
    question: 'Servers, clients, and routers:',
    options: ['Are the same thing', 'Work together to transmit data on the Internet', 'Only exist in Python', 'Store passwords'],
    correctIndex: 1,
    topic: 'Internet Systems',
    explanation: 'Servers provide resources, clients request them, and routers direct data between networks. Together they form the backbone of Internet communication.',
  },
  {
    id: 6,
    question: 'HTML is used to:',
    options: ['Write Python code', 'Structure content on webpages', 'Encrypt data', 'Run databases'],
    correctIndex: 1,
    topic: 'HTML',
    explanation: 'HTML (HyperText Markup Language) uses tags to structure content on the web—text, images, links, headings, and more. It defines the layout of a webpage.',
  },
  {
    id: 7,
    question: 'Devices on a network need unique addresses (IP addresses) to:',
    options: ['Increase speed', 'Ensure data reaches the right destination', 'Compress files', 'Display images'],
    correctIndex: 1,
    topic: 'Addressing',
    explanation: 'IP addresses uniquely identify devices so that when you send data over the Internet, it knows exactly where to go—like a mailing address for computers.',
  },
  {
    id: 8,
    question: 'Routing on the Internet:',
    options: ['Deletes data', 'Determines the path data takes to reach its destination', 'Compresses files', 'Creates websites'],
    correctIndex: 1,
    topic: 'Routing',
    explanation: 'Routing is the process of determining the best path for data to travel from sender to receiver. Routers make decisions to direct packets along the way.',
  },
  {
    id: 9,
    question: 'When data is sent over the Internet, it is typically split into:',
    options: ['One large file', 'Small pieces called packets', 'Binary only', 'Strings'],
    correctIndex: 1,
    topic: 'Packets',
    explanation: 'Data is split into small pieces called packets. Each packet travels independently and is reassembled at the destination. This makes transmission more efficient.',
  },
  {
    id: 10,
    question: 'HTTPS helps:',
    options: ['Speed up the Internet', 'Secure web communication by encrypting data', 'Store cookies', 'Display HTML'],
    correctIndex: 1,
    topic: 'HTTPS',
    explanation: 'HTTPS (HTTP Secure) encrypts data between your browser and the website. The "S" means your connection is protected from eavesdropping and tampering.',
  },
  {
    id: 11,
    question: 'DNS (Domain Name System) is responsible for:',
    options: ['Compressing websites', 'Converting domain names (like google.com) to IP addresses', 'Creating passwords', 'Storing lists'],
    correctIndex: 1,
    topic: 'DNS',
    explanation: 'DNS translates human-readable domain names into the IP addresses that computers use to find each other. You type "example.com" and DNS finds the right server.',
  },
  {
    id: 12,
    question: 'Fault tolerance means systems:',
    options: ['Never fail', 'Continue working despite some failures', 'Are always fast', 'Require no maintenance'],
    correctIndex: 1,
    topic: 'Fault Tolerance',
    explanation: 'Fault tolerance is the ability of a system to keep working even when parts of it fail. Redundancy and backup systems help achieve this.',
  },
  {
    id: 13,
    question: 'In parallel computing:',
    options: ['One task runs at a time', 'Multiple tasks run at the same time', 'Data is never split', 'The Internet is slower'],
    correctIndex: 1,
    topic: 'Parallel Computing',
    explanation: 'Parallel computing runs multiple tasks simultaneously, often on multiple processors. This can significantly speed up complex calculations.',
  },
  {
    id: 14,
    question: 'In distributed computing:',
    options: ['All work is done on one computer', 'Tasks are spread across multiple computers', 'Data cannot be shared', 'Packets are not used'],
    correctIndex: 1,
    topic: 'Distributed Computing',
    explanation: 'Distributed computing spreads tasks across many computers that work together. The Internet itself is an example—many machines cooperate to deliver content.',
  },
  {
    id: 15,
    question: 'Cybersecurity focuses on:',
    options: ['Making websites faster', 'Protecting systems and data from attacks', 'Creating new programming languages', 'Designing HTML'],
    correctIndex: 1,
    topic: 'Cybersecurity Overview',
    explanation: 'Cybersecurity protects computer systems, networks, and data from unauthorized access, attacks, and data theft. It is essential for keeping information safe.',
  },
  {
    id: 16,
    question: 'PII stands for:',
    options: ['Personal Internet Identifier', 'Personally Identifiable Information', 'Programming Input Interface', 'Protected Information Index'],
    correctIndex: 1,
    topic: 'PII',
    explanation: 'PII (Personally Identifiable Information) is any data that can be used to identify a specific person—name, address, SSN, email, etc. It must be protected.',
  },
  {
    id: 17,
    question: 'Cookies are small pieces of data that:',
    options: ['Encrypt your password', 'Websites store on your device to remember information', 'Delete your browsing history', 'Speed up DNS'],
    correctIndex: 1,
    topic: 'Cookies',
    explanation: 'Cookies are small files websites store on your device. They can remember login status, preferences, and track activity. They can raise privacy concerns.',
  },
  {
    id: 18,
    question: 'Internet privacy concerns include:',
    options: ['How fast data travels', 'How data is collected, used, and who has access to it', 'The number of routers', 'HTML structure'],
    correctIndex: 1,
    topic: 'Internet Privacy',
    explanation: 'Internet privacy involves concerns about who collects your data, how it is used, and whether you have control. Users should be aware of tracking and data sharing.',
  },
  {
    id: 19,
    question: 'A digital footprint is:',
    options: ['A type of encryption', 'The data you leave online through your activities', 'A programming loop', 'A network router'],
    correctIndex: 1,
    topic: 'Digital Footprint',
    explanation: 'Your digital footprint is the trail of data you create online—posts, searches, purchases, etc. It can be long-lasting and affect your reputation.',
  },
  {
    id: 20,
    question: 'Strong passwords are typically:',
    options: ['Short and simple', 'Long and unique', 'Your name and birth year', 'The same for all accounts'],
    correctIndex: 1,
    topic: 'Passwords',
    explanation: 'Strong passwords are long, unique, and combine letters, numbers, and symbols. They protect accounts from unauthorized access. Never reuse passwords across sites.',
  },
  {
    id: 21,
    question: 'Cryptography is used to:',
    options: ['Design websites', 'Encode information to keep it secret from unauthorized users', 'Create lists in Python', 'Route packets'],
    correctIndex: 1,
    topic: 'Cryptography',
    explanation: 'Cryptography uses mathematical techniques to encode information. Only authorized users with the right key can decrypt and read it. It secures sensitive data.',
  },
  {
    id: 22,
    question: 'Encryption:',
    options: ['Makes data easier to read', 'Converts readable data into unreadable form that requires a key to decrypt', 'Deletes old data', 'Speeds up the Internet'],
    correctIndex: 1,
    topic: 'Encryption',
    explanation: 'Encryption transforms readable data (plaintext) into unreadable form (ciphertext). Only someone with the correct key can decrypt it back to readable form.',
  },
  {
    id: 23,
    question: 'Python lists allow you to:',
    options: ['Only read values', 'Store and modify data easily', 'Encrypt passwords', 'Create the Internet'],
    correctIndex: 1,
    topic: 'Lists in Python',
    explanation: 'Lists in Python are mutable—you can add, remove, and change items. They make it easy to work with collections of related data in your programs.',
  },
  {
    id: 24,
    question: 'A protocol in networking is:',
    options: ['A type of cookie', 'A set of rules that define how devices communicate', 'A Python list', 'An encryption key'],
    correctIndex: 1,
    topic: 'Internet Protocols',
    explanation: 'Protocols are agreed-upon rules that devices use to communicate. TCP/IP, HTTP, and HTTPS are examples. They ensure everyone "speaks the same language."',
  },
  {
    id: 25,
    question: 'Redundancy in networks helps:',
    options: ['Delete duplicate data', 'Prevent system failure by having backup paths', 'Simplify passwords', 'Reduce packet size'],
    correctIndex: 1,
    topic: 'Redundancy',
    explanation: 'Redundancy means having backup or alternative paths. If one route fails, data can still reach its destination through another path. It improves reliability.',
  },
  {
    id: 26,
    question: 'A client in a network:',
    options: ['Only sends data', 'Requests and receives resources from servers', 'Encrypts all packets', 'Creates DNS records'],
    correctIndex: 1,
    topic: 'Clients and Servers',
    explanation: 'A client is a device or program that requests services or resources. Your web browser is a client that requests web pages from servers.',
  },
  {
    id: 27,
    question: 'Wired and wireless networks both:',
    options: ['Use the same physical cables', 'Connect devices to share data', 'Require no addressing', 'Cannot use encryption'],
    correctIndex: 1,
    topic: 'Networks',
    explanation: 'Both wired (Ethernet) and wireless (Wi-Fi) networks connect devices to share data. They use different physical means but serve the same purpose.',
  },
  {
    id: 28,
    question: 'When you visit a website, your browser:',
    options: ['Only receives data', 'Acts as a client requesting content from a server', 'Creates the HTML', 'Encrypts the DNS'],
    correctIndex: 1,
    topic: 'Client-Server Model',
    explanation: 'Your browser acts as a client. It sends a request to the server hosting the website, and the server responds with the webpage content (HTML, images, etc.).',
  },
  {
    id: 29,
    question: 'Protecting your PII online is important because:',
    options: ['It slows down websites', 'It can be used for identity theft or misuse if exposed', 'Routers require it', 'Packets need it'],
    correctIndex: 1,
    topic: 'PII and Privacy',
    explanation: 'PII can be misused for identity theft, fraud, or privacy violations. Protecting it—through strong passwords, careful sharing, and encryption—is essential.',
  },
  {
    id: 30,
    question: 'Understanding pseudocode helps when:',
    options: ['Installing routers', 'Converting algorithm logic into actual code', 'Encrypting cookies', 'Building physical networks'],
    correctIndex: 1,
    topic: 'Reading Pseudocode',
    explanation: 'Pseudocode bridges the gap between an idea and working code. It helps you plan the logic first, then translate it into Python or any programming language.',
  },
];
